---
################################################################################
### tasks file for ar-vim-setup ################################################
################################################################################

################################################################################
### Get distro information (name, version, ...)
################################################################################
- name: "Get \"distro\" related information"
  import_tasks: "1_get-common-distro-infos.yml"

################################################################################
### Install all packages defined in defaults/* and/or var/*
################################################################################
- name: "Install required packages"
  package:
    name: "{{ item.name }}"
    state: present
  loop: "{{ packages }}"

################################################################################
### Install vim for all defined users
################################################################################
- name: "Create vim directory structure for all defined users"
  file:
    path: "{{ item[0].user_dir }}/{{ item[1].vim_cfg_dir }}"
    group: "{{ item[0].user_group }}"
    owner: "{{ item[0].user_name }}"
    state: directory
  loop: "{{ users | product(vim_config_directories) | list }}"

- name: "Download/Install \"vim-plug\" as plugin manager"
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ item.user_dir }}/{{ vim_base_config_dir }}/autoload"
    group: "{{ item.user_group }}"
    owner: "{{ item.user_name }}"
  loop: "{{ users }}"

- name: "Install additional items required by vim"
  git:
    repo: "{{ item[1].repo }}"
    dest: "{{ item[0].user_dir }}/{{ item[1].dest }}"
    version: "{{ item[1].version  }}"
  loop: "{{ users | product(repositories) | list }}"

- name: "Change to correct ownership of the previous step"
  file:
    path: "{{ item[0].user_dir }}/{{ item[1].dest }}"
    group: "{{ item[0].user_group }}"
    owner: "{{ item[0].user_name }}"
    recurse: yes
    state: directory
  loop: "{{ users | product(repositories) | list }}"

- name: "Copy individual filetype plugin to vim directory of all defined users"
  copy:
    src: files/ftplugin
    dest: "{{ item.user_dir }}/{{ vim_base_config_dir }}"
    group: "{{ item.user_group }}"
    owner: "{{ item.user_name }}"
  loop: "{{ users }}"

- name: "Copy .vimrc to users directory"
  copy:
    src: files/.vimrc
    dest: "{{ item.user_dir }}"
    group: "{{ item.user_group }}"
    owner: "{{ item.user_name }}"
  loop: "{{ users }}"
