---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: test_ar-vim-setup_ubuntu2004_docker
    image: ubuntu:20.04
    pre_build_image: false
  - name: test_ar-vim-setup_ubuntu2010_docker
    image: ubuntu:20.10
    pre_build_image: false
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: True
verifier:
  name: ansible
