---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: test_vim-setup_ubuntu2004_docker
    image: ubuntu:20.04
    pre_build_image: false
provisioner:
  name: ansible
verifier:
  name: ansible
